import { Link } from "react-router-dom";

const pages = {
  about: { kicker: "A MODERN BULLION DESK", title: "Precious metals, without the mystery.", lead: "GoldOnTheSpot is built around live market pricing, secure ordering, and responsive support.", sections: [["Live market pricing", "Eligible product prices refresh with current metal markets. The secure checkout recalculates the total before accepting the order."], ["Careful fulfillment", "Inventory is reserved when an order is placed. Payment is reviewed before fulfillment, and precious-metal shipments require the appropriate insurance and signature service."], ["Support for serious purchases", "Whether you are buying one coin or discussing a larger order, our team can help with product selection, payment timing, and fulfillment questions."]] },
  shipping: { kicker: "FULFILLMENT", title: "Shipping and insurance", lead: "Bullion requires more care than an ordinary package. Our fulfillment rules are designed around value, verification, and safe delivery.", sections: [["Insured shipment", "Orders are shipped using a service appropriate for the declared value. Insurance coverage and carrier rules are confirmed before release."], ["Signature required", "An adult signature may be required. High-value orders cannot be left unattended, redirected casually, or shipped to an unverified address."], ["Processing time", "Orders ship only after cleared payment and final review. Checks may require additional clearance time. Tracking appears in your account when the order is released."]] },
  terms: { kicker: "LEGAL", title: "Terms of purchase", lead: "These operational terms are a launch draft and must be reviewed by qualified counsel before public payment acceptance.", sections: [["Market pricing", "Precious-metal prices fluctuate. A submitted order uses the server-calculated locked price shown in the confirmation. Expired or unpaid orders may be cancelled."], ["Payment", "Orders are not paid until the approved payment method is completed. Card invoice requests may include the disclosed processing surcharge."], ["Cancellations and returns", "Bullion orders are market transactions and may not be cancellable or returnable after price confirmation. Any exception must be approved in writing."]] },
  privacy: { kicker: "PRIVACY", title: "Privacy policy", lead: "We collect only the information needed to operate customer accounts, process orders, prevent fraud, and provide support.", sections: [["Information collected", "Account identifiers, contact information, shipping details, order history, and operational security records may be collected."], ["How information is used", "Information is used to authenticate customers, manage orders, communicate payment and shipping instructions, prevent abuse, and comply with applicable obligations."], ["Payment data", "This website does not collect or store full payment-card numbers. Card payments, when enabled, are completed through an approved payment provider."]] },
};

export default function InfoPage({ type }) {
  const page = pages[type] || pages.about;
  return <><section className="info-hero"><div className="container"><span className="eyebrow">{page.kicker}</span><h1>{page.title}</h1><p>{page.lead}</p></div></section><section className="section"><div className="container prose-layout"><aside><b>GoldOnTheSpot</b><span>Precious metals, right now.</span><Link to="/shop">Shop bullion →</Link><Link to="/support">Customer support →</Link></aside><article>{page.sections.map(([title, body]) => <section key={title}><h2>{title}</h2><p>{body}</p></section>)}{["terms", "privacy"].includes(type) && <p className="policy-date">Last updated: July 15, 2026</p>}<div className="legal-note">Questions about this page? <Link to="/support">Open the customer support center</Link> or email <a href="mailto:support@goldonthespot.com">support@goldonthespot.com</a>.</div></article></div></section></>;
}
